package com.czsy.bean.gongyingzhanzz

import com.contrarywind.interfaces.IPickerViewData

data class OrderItmeBean(
        val anJianDanSid: Any,
        val beiZhu: Any,
        val callerPhone: Any,
        val changZhan: String,
        val changZhanId: String,
        val chuangJianRiQi: String,
        val details: List<Detail>,
        val diZhi: String,
        val dingDanHao: String,
        val dingDanLeiXing: Int,
        val dingDanLeiXingName: String,
        val enableCancel: Boolean,
        val enableFenPei: Boolean,
        val fuJiaFei: Double,
        val gongYingZhan: String,
        val gongYingZhanId: String,
        val huiShouGangPing: Int,
        val id: String,
        val jiFen: Any,
        val keFu: Any,
        val keFuId: Any,
        val keHuBianHao: String,
        val keHuDianHua: String,
        val keHuId: String,
        val keHuLaiYuan: String,
        val keHuLeiXing: Int,
        val keHuLeiXingName: String,
        val keHuMing: String,
        val laiYuan: Int,
        val laiYuanName: String,
        val lastUpdateDate: String,
        val louCeng: Int,
        val peiSongGangPing: Int,
        val peiSongYuan: String,
        val peiSongYuanDianHua: String,
        val peiSongYuanId: String,
        val pingJiaStatus: Int,
        val pingJiaStatusName: String,
        val qiWangPeiSongRiQi: Any,
        val qianKuanZhiFuFangShi: Int,
        val qianKuanZhiFuFangShiName: String,
        val qiangZhiAnJian: Any,
        val shangPinJinE: Double,
        val shiFouCuiDan: Int,
        val shiFouKaiFaPiao: Any,
        val shiShouJinE: Double,
        val shouYaJinJinE: Double,
        val status: Int,
        val statusName: String,
        val tuiDanYuanYin: Any,
        val tuiQiJinE: Double,
        val wanChengRiQi: String,
        val xiaDanRen: String,
        val xiaDanRenId: String,
        val yaJinJinE: Double,
        val yingShouJinE: Double,
        val yuQi: Double,
        val yunFei: Double,
        val zheJiuGangPing: Int,
        val zhiFuFangShi: Int,
        val zhiFuFangShiName: String
)

data class Detail(
        val count: Int,
        val guiGe: Int,
        val price: Double,
        val shangPingMingCheng: String,
        val qiTiLeiXingName: String,
        val type: String,
        val zongJinE: Double
)

data class PeisongyuanBean(
        val id: String,
        val userName: String,
        val telNum: String

)

data class WeixiuBean(
        val baoXiuReason: String,
        val beiZhu: String,
        val changZhan: String,
        val changZhanId: String,
        val chuangJianRiQi: String,
        val diZhi: String,
        val dingDanHao: String,
        val enableCancel: Boolean,
        val enableFenPei: Boolean,
        val gongYingZhan: String,
        val gongYingZhanId: String,
        val id: String,
        val keFu: String,
        val keFuId: Any,
        val keHuBianHao: String,
        val keHuDianHua: String,
        val keHuId: String,
        val keHuLeiXing: Int,
        val keHuLeiXingName: String,
        val keHuMing: String,
        val laiYuan: Int,
        val laiYuanName: String,
        val lastUpdateDate: String,
        val peiSongYuan: Any,
        val peiSongYuanId: Any,
        val qiWangPeiSongRiQi: Any,
        val status: Int,
        val statusName: String,
        val tuiDanYuanYin: Any,
        val type: Any,
        val typeName: Any,
        val wanChengRiQi: String,
        val xiaDanRen: String,
        val xiaDanRenId: String
)

data class AnjianBean(
        val anJianQianMing: Any,
        val anJianRiQi: String,
        val anJianTuPian: Any,
        val anJianWenTiList: List<Any>,
        val beiZhu: String,
        val changZhan: String,
        val changZhanId: String,
        val chuangJianRiQi: String,
        val diZhi: String,
        val dingDanHao: String,
        val enableCancel: Boolean,
        val enableFenPei: Boolean,
        val gongYingZhan: String,
        val gongYingZhanId: String,
        val id: String,
        val keFu: String,
        val keFuId: Any,
        val keHuDianHua: String,
        val keHuId: String,
        val keHuLeiXing: Int,
        val keHuLeiXingName: String,
        val keHuMing: String,
        val laiYuan: Any,
        val laiYuanName: Any,
        val lastUpdateDate: String,
        val peiSongYuan: Any,
        val peiSongYuanId: Any,
        val qiWangPeiSongRiQi: Any,
        val status: Int,
        val statusName: String,
        val tuiDanYuanYin: Any,
        val wanChengRiQi: String

)

data class HuikuDetilsBean(
        val baoFeiRiQi: String,
        val changZhan: String,
        val changZhanId: String,
        val chongQiCiShu: Int,
        val chuangJianRiQi: String,
        val gangPingHao: String,
        val gongYingZhan: String,
        val gongYingZhanId: String,
        val guiGe: Int,
        val guiGeName: String,
        val id: String,
        val jianDangDanWei: String,
        val jianDangDanWeiId: String,
        val jianDangRenYuan: String,
        val jianDangRenYuanId: String,
        val jianDangRiQi: String,
        val jingZhong: Double,
        val keHuId: Any,
        val notMoveDay: Int,
        val peiSongYuanId: String,
        val qiTiLeiXing: String,
        val qiTiLeiXingId: Int,
        val shangCiJianXiuRiQi: String,
        val shengChanChangJia: String,
        val shengChanChangJiaId: Any,
        val shengChanRiQi: String,
        val shiYongNianXian: Any,
        val status: Int,
        val statusName: String,
        val xiaCiJianXiuRiQi: String,
        val xinPianHao: String,
        val yuQi: Double,
        val yuQiJinE: Any,
        val yuQiLuRuRenYuanId: Any,
        val yuQiStatus: Int,
        val yuQiStatusName: String,
        val yunShuYuanId: String,
        val zhongLiang: Any,
        val zuiHouChongQiRiQi: String,
        val zuiHouWeiZhi: Int,
        val zuiHouWeiZhiHolderName: String,
        val zuiHouWeiZhiName: String
)

data class KucunBean(
        val gangPing10KGCount: Int,
        val gangPing15KGCount: Int,
        val gangPing50KGCount: Int,
        val gangPing50KGIICount: Int,
        val gangPing50KGYeCount: Int,
        val gangPing5KGCount: Int,
        val shiShouYaJin: Int,
        val sum: Int,
        val xiaoShouE: Int
)

data class KucunItemBean(
        val baoFeiRiQi: String,
        val changZhan: String,
        val changZhanId: String,
        val chongQiCiShu: Int,
        val chuangJianRiQi: String,
        val gangPingHao: String,
        val gongYingZhan: String,
        val gongYingZhanId: String,
        val guiGe: Int,
        val guiGeName: String,
        val id: String,
        val jianDangDanWei: String,
        val jianDangDanWeiId: String,
        val jianDangRenYuan: String,
        val jianDangRenYuanId: String,
        val jianDangRiQi: String,
        val jingZhong: Int,
        val keHuId: Any,
        val notMoveDay: Int,
        val peiSongYuanId: String,
        val qiTiLeiXing: String,
        val qiTiLeiXingId: Int,
        val shangCiJianXiuRiQi: String,
        val shengChanChangJia: String,
        val shengChanChangJiaId: Any,
        val shengChanRiQi: String,
        val shiYongNianXian: Any,
        val status: Int,
        val statusName: String,
        val xiaCiJianXiuRiQi: String,
        val xinPianHao: String,
        val yuQi: Int,
        val yuQiJinE: Any,
        val yuQiLuRuRenYuanId: Any,
        val yuQiStatus: Int,
        val yuQiStatusName: String,
        val yunShuYuanId: String,
        val zhongLiang: Any,
        val zuiHouChongQiRiQi: String,
        val zuiHouWeiZhi: Int,
        val zuiHouWeiZhiHolderName: String,
        val zuiHouWeiZhiName: String
)

fun anjianToString(bean: AnjianBean): String {

    val str = "${bean.anJianQianMing} *--*-***-*-**"
    return str
}